/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_JNIWrapper */

#ifndef _Included_util_JNIWrapper
#define _Included_util_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_JNIWrapper
 * Method:    atEntry
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_util_JNIWrapper_atEntry
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
